@extends('layouts.app')

@section('meta')
    <meta name="twitter:card" content="photo" />
    <meta name="twitter:site" content="" />
    <meta name="twitter:image" content="{{ route('frontend.show.image', ['uuid' => $image->image_share_hash, 'full' => true]) }}" />
    <meta name="twitter:url" content="{{ route('frontend.show.image', $image->image_share_hash) }}" />
@endsection

@section('content')
    <div class="container">

        @if (AWSImage::getFileVisibility($image->id) === 'private' && $image->user_id === Auth::id())
            <div class="alert alert-warning">
                <strong>NOTE! </strong> Current image is set to private. You can only see this image when you are logged in and are owner of the image. To make this image public head over to
                <a href="{{ route('user.image.settings', $image->image_share_hash) }}"><strong>Settings</strong></a> and set visibility to public
            </div>

        @elseif (request()->get('expires'))
            <div class="alert alert-warning">
                <strong>NOTE! </strong> You are accessing this image via private URL. This URL will expire in {{ \Carbon\Carbon::createFromTimestamp(request()->get('expires'))->fromNow() }}. This URL was generated by {{ $image->user->name}}
            </div>
        @endif

        <div class="card shadow-sm">
            <div class="card-body text-center">
                <a href="{{ AWSImage::generateTempLink($image->image_name, 5) }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ AWSImage::generateTempLink($image->image_name, 5) }}" class="img-fluid rounded">
                </a>
            </div>
            <div class="card-footer">
                <span>Uploaded: {{ $image->created_at->diffForHumans() }}</span> | <span><a target="_blank" href="{{ url()->current().'?'.http_build_query(array_merge(request()->all(),['full' => 'true'])) }}">Original Url</a></span> | <span>Uploaded By: {{ $image->user->name}}</span>
            </div>
        </div>
    </div>


    <div class="modal" id="viewImg" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="imgViewer" style="overflow-x: scroll;">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('js')
    <script>
        $(document).on("click", '[data-toggle="lightbox"]', function(event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
    </script>
@endsection
